FROM golang:1.16.2-alpine3.13 as builder

ARG mock_resource_version

RUN apk add git
RUN git clone --depth 1 --branch v${mock_resource_version} https://github.com/concourse/mock-resource.git /src/mock-resource
WORKDIR /src/mock-resource
ENV CGO_ENABLED 0
RUN go get -d ./...
RUN go build -o /assets/in ./cmd/in
RUN go build -o /assets/out ./cmd/out
RUN go build -o /assets/check ./cmd/check

FROM alpine:edge AS resource
RUN apk add --no-cache bash wget netcat-openbsd
COPY --from=builder assets/ /opt/resource/
RUN chmod +x /opt/resource/*

FROM resource
