FROM golang:1.16.2-alpine3.13 as builder

ARG docker_image_resource_version

RUN apk add git
RUN git clone --depth 1 --branch v${docker_image_resource_version} https://github.com/concourse/docker-image-resource.git /src/docker-image-resource
WORKDIR /src/docker-image-resource

ENV CGO_ENABLED 0
RUN mkdir -p /assets
RUN go get -d ./...
RUN go build -o /assets/check github.com/concourse/docker-image-resource/cmd/check
RUN go build -o /assets/print-metadata github.com/concourse/docker-image-resource/cmd/print-metadata
RUN go build -o /assets/ecr-login github.com/awslabs/amazon-ecr-credential-helper/ecr-login/cmd
RUN set -e; \
    for pkg in $(go list ./...); do \
      go test -o "/tests/$(basename $pkg).test" -c $pkg; \
    done
RUN cp ./assets/* /assets/

# stage: resource
FROM alpine:edge AS resource

RUN apk --no-cache add \
      bash \
      docker \
      jq \
      ca-certificates \
      xz \
      util-linux \
      tar \
    ;
COPY --from=builder assets/ /opt/resource/
RUN chmod +x /opt/resource/*
RUN ln -s /opt/resource/ecr-login /usr/local/bin/docker-credential-ecr-login

# final output stage
FROM resource