FROM golang:1.16.2-alpine3.13 as builder

ARG github_release_resource_version

RUN apk add git
RUN git clone --depth 1 --branch v${github_release_resource_version} https://github.com/concourse/github-release-resource.git /src/github-release-resource
WORKDIR /src/github-release-resource
ENV CGO_ENABLED 0
RUN go mod vendor
RUN go build -o /assets/in ./cmd/in
RUN go build -o /assets/out ./cmd/out
RUN go build -o /assets/check ./cmd/check

FROM alpine:edge AS resource
RUN apk add --no-cache bash tzdata ca-certificates
COPY --from=builder assets/ /opt/resource/
RUN chmod +x /opt/resource/*

FROM resource
