FROM golang:1.16.2-alpine3.13 as builder

ARG slack_alert_resource_version

RUN apk add git
RUN git clone --depth 1 --branch v${slack_alert_resource_version} https://github.com/arbourd/concourse-slack-alert-resource.git /src/slack-alert-resource
WORKDIR /src/slack-alert-resource
ENV CGO_ENABLED 0
ENV GO111MODULE on
RUN go mod download
RUN go build -o /assets/in ./in
RUN go build -o /assets/out ./out
RUN go build -o /assets/check ./check

FROM alpine:edge AS resource
RUN apk add --no-cache ca-certificates
COPY --from=builder assets/ /opt/resource/
RUN chmod +x /opt/resource/*

FROM resource
