FROM golang:1.16.2-alpine3.13 as builder

ARG s3_resource_version

RUN apk add git
RUN git clone --depth 1 --branch v${s3_resource_version} https://github.com/concourse/s3-resource.git /src/s3-resource
WORKDIR /src/s3-resource
ENV CGO_ENABLED 0
RUN go get -d ./...
RUN go build -o /assets/in ./cmd/in
RUN go build -o /assets/out ./cmd/out
RUN go build -o /assets/check ./cmd/check

FROM alpine:edge AS resource
RUN apk add --no-cache tzdata ca-certificates unzip zip gzip tar
COPY --from=builder assets/ /opt/resource/
RUN chmod +x /opt/resource/*

FROM resource
